- name: Setup Personal Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "/home/{{ ansible_user }}"
    zsh_custom: "{{ home_dir }}/.oh-my-zsh/custom"
    conda_dir: "{{ home_dir }}/conda"
  tasks:
    - block:
      - name: Update and upgrade the system
        become: true
        apt:
          update_cache: true
          upgrade: dist

      - name: Install essential packages
        become: true
        apt:
          name:
            - zsh
            - git
            - curl
            - wget
            - build-essential
            - fzf
            - htop
            - lm-sensors
            - sqlite3
            - postgresql-client
            - p7zip-full
            - pkg-config
            - libssl-dev
          state: present

      - name: Install snaps (classic confinement)
        become: true
        community.general.snap:
          classic: true
          name:
            - kubectl
            - helm
            - code

      - name: Install docker
        include_role:
          name: geerlingguy.docker
          apply:
            become: true
        vars:
          docker_users:
            - "{{ ansible_user }}"

      - name: Install minikube
        include_role:
          name: gantsign.minikube

      - name: Install Rust toolchain
        shell: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        args:
          executable: /usr/bin/zsh
          creates: "{{ home_dir }}/.cargo"

      - name: Cargo Install
        community.general.cargo:
          executable: "{{ home_dir }}/.cargo/bin/cargo"
          locked: true
          name:
            - tealdeer
            - nu

      - name: Install conda
        shell: |
          curl -fsSLo conda-installer.sh \
            https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh
          sh conda-installer.sh -b -p "{{ conda_dir }}"
          rm conda-installer.sh
        args:
          executable: /usr/bin/zsh
          creates: "{{ conda_dir }}"

      - name: Change default shell to Zsh
        become: true
        user:
          name: "{{ ansible_user }}"
          shell: /usr/bin/zsh

      - name: Install Oh-My-Zsh
        shell: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        args:
          executable: /usr/bin/zsh
          creates: "{{ home_dir }}/.oh-my-zsh"

      - name: Install Powerlevel10k theme
        git:
          repo: https://github.com/romkatv/powerlevel10k.git
          dest: "{{ zsh_custom }}/themes/powerlevel10k"
          depth: 1

      - name: Install Zsh Plugins
        git:
          repo: "{{ item }}"
          dest: "{{ zsh_custom }}/plugins/{{ item | basename }}"
          depth: 1
        with_items:
          - https://github.com/esc/conda-zsh-completion
          - https://github.com/zdharma-continuum/fast-syntax-highlighting
          - https://github.com/Aloxaf/fzf-tab
          - https://github.com/zsh-users/zsh-autosuggestions

      - name: Configure additional completions
        shell: |
          curl https://raw.githubusercontent.com/tealdeer-rs/tealdeer/refs/heads/main/completion/zsh_tealdeer \
            -o /home/user/.oh-my-zsh/custom/completions/_tldr \
            --create-dirs
        args:
          creates: "{{ zsh_custom }}/completions/_tldr"

      - name: Configure .zshrc
        template:
          src: .zshrc.j2
          dest: "{{ ansible_user }}/.zshrc"
          backup: true

      - name: Configure p10k
        copy:
          src: .p10k.zsh
          dest: "{{ ansible_user }}/.p10k.zsh"
          backup: true

      - name: Configure conda
        copy:
          src: .condarc
          dest: "{{ ansible_user }}/.condarc"
          backup: true

      - name: Install a Nerd Font
        become: true
        shell: |
          cd /usr/share/fonts/truetype
          wget https://github.com/vercel/geist-font/releases/download/1.4.01/GeistMono-1.4.01.zip
          unzip GeistMono-1.4.01 -d ./geist-mono
          rm GeistMono-1.4.01
          fc-cache -fv
        args:
          executable: /usr/bin/zsh
          creates: /usr/share/fonts/truetype/geist-mono
