- name: Setup Personal Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: /home/{{ ansible_user }}
    zsh_custom: /home/{{ ansible_user }}/.oh-my-zsh/custom
  tasks:
    - block:
      - name: Update and upgrade the system
        become: true
        apt:
          update_cache: true
          upgrade: dist

      - name: Install essential packages
        become: true
        apt:
          name:
            - zsh
            - git
            - curl
            - wget
            - build-essential
            - fzf
          state: present

      - name: Install Rust toolchain
        shell: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        args:
          executable: /usr/bin/zsh
          creates: "{{ home_dir }}/.cargo"

      - name: Cargo Install
        community.general.cargo:
          executable: "{{ home_dir }}/.cargo/bin/cargo"
          name:
            - tealdeer

      - name: Install conda
        shell: |
          curl -fsSLo conda-installer.sh \
            https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh
          sh conda-installer.sh -b -p "{{ home_dir }}/conda"
          rm conda-installer.sh
        args:
          executable: /usr/bin/zsh
          creates: "{{ home_dir }}/conda"

      - name: Change default shell to Zsh
        become: true
        user:
          name: "{{ ansible_user }}"
          shell: /usr/bin/zsh

      - name: Install Oh-My-Zsh
        shell: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        args:
          executable: /usr/bin/zsh
          creates: "{{ home_dir }}/.oh-my-zsh"

      - name: Install Powerlevel10k theme
        git:
          repo: https://github.com/romkatv/powerlevel10k.git
          dest: "{{ zsh_custom }}/themes/powerlevel10k"
          depth: 1

      - name: Install Zsh Plugins
        git:
          repo: "{{ item }}"
          dest: "{{ zsh_custom }}/plugins/{{ item | basename }}"
          depth: 1
        with_items:
          - https://github.com/esc/conda-zsh-completion
          - https://github.com/zdharma-continuum/fast-syntax-highlighting
          - https://github.com/Aloxaf/fzf-tab
          - https://github.com/zsh-users/zsh-autosuggestions

      - name: Configure additional completions
        shell: |
          curl https://raw.githubusercontent.com/tealdeer-rs/tealdeer/refs/heads/main/completion/zsh_tealdeer \
            -o /home/user/.oh-my-zsh/custom/completions/_tldr \
            --create-dirs
        args:
          creates: "{{ zsh_custom }}/completions/_tldr"

      - name: Configure .zshrc
        register: copy_zshrc
        copy:
          src: .zshrc
          dest: ~/.zshrc

      - name: Conda init
        shell: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda init zsh
        args:
          executable: /usr/bin/zsh
        when: copy_zshrc.changed

      - name: Configure p10k
        copy:
          src: .p10k.zsh
          dest: ~/.p10k.zsh

      - name: Configure conda
        copy:
          src: .condarc
          dest: ~/.condarc
